var sweety = "Sweety", cutie="Cutie";
console.log("Values Before Swapping");
console.log(sweety, cutie);
var temp;
temp=sweety;
sweety=cutie;
cutie=temp;
console.log("Values After Swapping");
console.log(sweety, cutie);
var num1=100, num2=200, num3=300;
console.log("Values before Swapping");
console.log(num1, num2, num3);
var temp1;
temp1 = num1;
num1=num2;
num2=num3;
num3=temp1;
console.log("Values after Swapping");
console.log(num1, num2, num3);